apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mantra-arc-ingress
  namespace: mantra-arc
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: mantra-arc.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mantra-arc-web
                port:
                  number: 3000
    - host: api-mantra-arc.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mantra-arc-api
                port:
                  number: 3012
